### ISSUE TITLE
Recomended link doesn't work!

### ISSUE THREAD

**Issue by AslanSN** [breatheco-de/exercise-terminal-challenge#16]
![imagen](https://user-images.githubusercontent.com/90191991/141681089-f31fd065-a6ba-42f6-80db-f5eed1259032.png)

**Comment by ElviraQDP** [comment]
Could you please specify which link? thanks!

**Comment by AslanSN** [comment]
![Broken link](https://user-images.githubusercontent.com/90191991/141811089-b00e1f05-4f8f-4632-8dfb-2c66481f8e76.png)
There

**Comment by ElviraQDP** [comment]
Thank you!

**Comment by ElviraQDP** [comment]
issue solved!! give it a couple of a hours and try again
